### ISSUE TITLE
snow layer in the air

### ISSUE THREAD

**Issue by efor89** [note3crafter/SnowMod#2]
hi i have the problem that the snow layer is in the air!

![Screenshot (67)](https://user-images.githubusercontent.com/67799203/100323783-89fcac80-2fc6-11eb-8ed5-6764b1bd57fb.png)

**Comment by note3crafter** [comment]
You have invisible Bedrock on the Top 👍 Remove it than will it work!

**Comment by efor89** [comment]
thx was not bedrock some other invisible block
